Name:           perl%{plv}-Business-ISBN-Data
Version:        20120719.001
Release:        1%{?dist}
Summary:        Data pack for Business::ISBN
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Business-ISBN-Data/
Source0:        http://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-Data-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl%{plv}
Requires:       perl%{plv}

%description
You don't need to load this module yourself in most cases. Business::ISBN
will load it when it loads.

%prep
%setup -q -n Business-ISBN-Data-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%{perl_vendorlib}/*
%{vendormandir}/man3/*

%changelog
* Thu Jul 31 2014 David E. Wheeler <david.wheeler@iovation.com> 20120719.001-1
- Specfile autogenerated by cpanspec 1.78.
