Name:           %{iov_prefix}-Sub-Name
Version:        0.07
Release:        1%{?dist}
Summary:        (re)name a sub
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Sub-Name/
Source0:        http://cpan.metacpan.org/authors/id/E/ET/ETHER/Sub-Name-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  %{iov_prefix}
Requires:       %{iov_prefix}

%description
This module has only one function, which is also exported by default:

%prep
%setup -q -n Sub-Name-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Sub*
%{_mandir}/man3/*

%changelog
* Thu Jul 31 2014 David E. Wheeler <david.wheeler@iovation.com> 0.07-1
- Specfile autogenerated by cpanspec 1.78.
